/*
 * This file is generated by jOOQ.
 */
package ch.martinelli.demo.nested.db.tables;


import ch.martinelli.demo.nested.db.Indexes;
import ch.martinelli.demo.nested.db.Keys;
import ch.martinelli.demo.nested.db.Public;
import ch.martinelli.demo.nested.db.tables.Product.ProductPath;
import ch.martinelli.demo.nested.db.tables.PurchaseOrder.PurchaseOrderPath;
import ch.martinelli.demo.nested.db.tables.records.OrderItemRecord;
import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrderItem extends TableImpl<OrderItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.order_item</code>
     */
    public static final OrderItem ORDER_ITEM = new OrderItem();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderItemRecord> getRecordType() {
        return OrderItemRecord.class;
    }

    /**
     * The column <code>public.order_item.id</code>.
     */
    public final TableField<OrderItemRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.order_item.quantity</code>.
     */
    public final TableField<OrderItemRecord, Integer> QUANTITY = createField(DSL.name("quantity"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.order_item.purchase_order_id</code>.
     */
    public final TableField<OrderItemRecord, Long> PURCHASE_ORDER_ID = createField(DSL.name("purchase_order_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.order_item.product_id</code>.
     */
    public final TableField<OrderItemRecord, Long> PRODUCT_ID = createField(DSL.name("product_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private OrderItem(Name alias, Table<OrderItemRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OrderItem(Name alias, Table<OrderItemRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.order_item</code> table reference
     */
    public OrderItem(String alias) {
        this(DSL.name(alias), ORDER_ITEM);
    }

    /**
     * Create an aliased <code>public.order_item</code> table reference
     */
    public OrderItem(Name alias) {
        this(alias, ORDER_ITEM);
    }

    /**
     * Create a <code>public.order_item</code> table reference
     */
    public OrderItem() {
        this(DSL.name("order_item"), null);
    }

    public <O extends Record> OrderItem(Table<O> path, ForeignKey<O, OrderItemRecord> childPath, InverseForeignKey<O, OrderItemRecord> parentPath) {
        super(path, childPath, parentPath, ORDER_ITEM);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class OrderItemPath extends OrderItem implements Path<OrderItemRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> OrderItemPath(Table<O> path, ForeignKey<O, OrderItemRecord> childPath, InverseForeignKey<O, OrderItemRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private OrderItemPath(Name alias, Table<OrderItemRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public OrderItemPath as(String alias) {
            return new OrderItemPath(DSL.name(alias), this);
        }

        @Override
        public OrderItemPath as(Name alias) {
            return new OrderItemPath(alias, this);
        }

        @Override
        public OrderItemPath as(Table<?> alias) {
            return new OrderItemPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.UX_ORDER_ITEM_PRODUCT_ID, Indexes.UX_ORDER_ITEM_PURCHASE_ORDER_ID);
    }

    @Override
    public UniqueKey<OrderItemRecord> getPrimaryKey() {
        return Keys.ORDER_ITEM_PKEY;
    }

    @Override
    public List<ForeignKey<OrderItemRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ORDER_ITEM__ORDER_ITEM_PRODUCT_ID_FKEY, Keys.ORDER_ITEM__ORDER_ITEM_PURCHASE_ORDER_ID_FKEY);
    }

    private transient ProductPath _product;

    /**
     * Get the implicit join path to the <code>public.product</code> table.
     */
    public ProductPath product() {
        if (_product == null)
            _product = new ProductPath(this, Keys.ORDER_ITEM__ORDER_ITEM_PRODUCT_ID_FKEY, null);

        return _product;
    }

    private transient PurchaseOrderPath _purchaseOrder;

    /**
     * Get the implicit join path to the <code>public.purchase_order</code>
     * table.
     */
    public PurchaseOrderPath purchaseOrder() {
        if (_purchaseOrder == null)
            _purchaseOrder = new PurchaseOrderPath(this, Keys.ORDER_ITEM__ORDER_ITEM_PURCHASE_ORDER_ID_FKEY, null);

        return _purchaseOrder;
    }

    @Override
    public OrderItem as(String alias) {
        return new OrderItem(DSL.name(alias), this);
    }

    @Override
    public OrderItem as(Name alias) {
        return new OrderItem(alias, this);
    }

    @Override
    public OrderItem as(Table<?> alias) {
        return new OrderItem(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderItem rename(String name) {
        return new OrderItem(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderItem rename(Name name) {
        return new OrderItem(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderItem rename(Table<?> name) {
        return new OrderItem(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderItem where(Condition condition) {
        return new OrderItem(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderItem where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderItem where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderItem where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrderItem where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrderItem where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrderItem where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrderItem where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderItem whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderItem whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
