/*
 * This file is generated by jOOQ.
 */
package ch.martinelli.demo.nested.db.tables;


import ch.martinelli.demo.nested.db.Indexes;
import ch.martinelli.demo.nested.db.Keys;
import ch.martinelli.demo.nested.db.Public;
import ch.martinelli.demo.nested.db.tables.Customer.CustomerPath;
import ch.martinelli.demo.nested.db.tables.OrderItem.OrderItemPath;
import ch.martinelli.demo.nested.db.tables.records.PurchaseOrderRecord;
import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PurchaseOrder extends TableImpl<PurchaseOrderRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.purchase_order</code>
     */
    public static final PurchaseOrder PURCHASE_ORDER = new PurchaseOrder();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PurchaseOrderRecord> getRecordType() {
        return PurchaseOrderRecord.class;
    }

    /**
     * The column <code>public.purchase_order.id</code>.
     */
    public final TableField<PurchaseOrderRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.purchase_order.order_date</code>.
     */
    public final TableField<PurchaseOrderRecord, LocalDateTime> ORDER_DATE = createField(DSL.name("order_date"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.purchase_order.customer_id</code>.
     */
    public final TableField<PurchaseOrderRecord, Long> CUSTOMER_ID = createField(DSL.name("customer_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private PurchaseOrder(Name alias, Table<PurchaseOrderRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PurchaseOrder(Name alias, Table<PurchaseOrderRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.purchase_order</code> table reference
     */
    public PurchaseOrder(String alias) {
        this(DSL.name(alias), PURCHASE_ORDER);
    }

    /**
     * Create an aliased <code>public.purchase_order</code> table reference
     */
    public PurchaseOrder(Name alias) {
        this(alias, PURCHASE_ORDER);
    }

    /**
     * Create a <code>public.purchase_order</code> table reference
     */
    public PurchaseOrder() {
        this(DSL.name("purchase_order"), null);
    }

    public <O extends Record> PurchaseOrder(Table<O> path, ForeignKey<O, PurchaseOrderRecord> childPath, InverseForeignKey<O, PurchaseOrderRecord> parentPath) {
        super(path, childPath, parentPath, PURCHASE_ORDER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PurchaseOrderPath extends PurchaseOrder implements Path<PurchaseOrderRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PurchaseOrderPath(Table<O> path, ForeignKey<O, PurchaseOrderRecord> childPath, InverseForeignKey<O, PurchaseOrderRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PurchaseOrderPath(Name alias, Table<PurchaseOrderRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PurchaseOrderPath as(String alias) {
            return new PurchaseOrderPath(DSL.name(alias), this);
        }

        @Override
        public PurchaseOrderPath as(Name alias) {
            return new PurchaseOrderPath(alias, this);
        }

        @Override
        public PurchaseOrderPath as(Table<?> alias) {
            return new PurchaseOrderPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.UX_PURCHASE_ORDER_CUSTOMER_ID);
    }

    @Override
    public UniqueKey<PurchaseOrderRecord> getPrimaryKey() {
        return Keys.PURCHASE_ORDER_PKEY;
    }

    @Override
    public List<ForeignKey<PurchaseOrderRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PURCHASE_ORDER__PURCHASE_ORDER_CUSTOMER_ID_FKEY);
    }

    private transient CustomerPath _customer;

    /**
     * Get the implicit join path to the <code>public.customer</code> table.
     */
    public CustomerPath customer() {
        if (_customer == null)
            _customer = new CustomerPath(this, Keys.PURCHASE_ORDER__PURCHASE_ORDER_CUSTOMER_ID_FKEY, null);

        return _customer;
    }

    private transient OrderItemPath _orderItem;

    /**
     * Get the implicit to-many join path to the <code>public.order_item</code>
     * table
     */
    public OrderItemPath orderItem() {
        if (_orderItem == null)
            _orderItem = new OrderItemPath(this, null, Keys.ORDER_ITEM__ORDER_ITEM_PURCHASE_ORDER_ID_FKEY.getInverseKey());

        return _orderItem;
    }

    @Override
    public PurchaseOrder as(String alias) {
        return new PurchaseOrder(DSL.name(alias), this);
    }

    @Override
    public PurchaseOrder as(Name alias) {
        return new PurchaseOrder(alias, this);
    }

    @Override
    public PurchaseOrder as(Table<?> alias) {
        return new PurchaseOrder(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PurchaseOrder rename(String name) {
        return new PurchaseOrder(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PurchaseOrder rename(Name name) {
        return new PurchaseOrder(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PurchaseOrder rename(Table<?> name) {
        return new PurchaseOrder(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurchaseOrder where(Condition condition) {
        return new PurchaseOrder(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurchaseOrder where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurchaseOrder where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurchaseOrder where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurchaseOrder where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurchaseOrder where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurchaseOrder where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PurchaseOrder where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurchaseOrder whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PurchaseOrder whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
