/*
 * This file is generated by jOOQ.
 */
package ch.martinelli.demo.nested.db.tables.records;


import ch.martinelli.demo.nested.db.tables.Customer;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomerRecord extends UpdatableRecordImpl<CustomerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.customer.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.customer.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.customer.first_name</code>.
     */
    public void setFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.customer.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.customer.last_name</code>.
     */
    public void setLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.customer.last_name</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.customer.street</code>.
     */
    public void setStreet(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.customer.street</code>.
     */
    public String getStreet() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.customer.postal_code</code>.
     */
    public void setPostalCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.customer.postal_code</code>.
     */
    public String getPostalCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.customer.city</code>.
     */
    public void setCity(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.customer.city</code>.
     */
    public String getCity() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomerRecord
     */
    public CustomerRecord() {
        super(Customer.CUSTOMER);
    }

    /**
     * Create a detached, initialised CustomerRecord
     */
    public CustomerRecord(Long id, String firstName, String lastName, String street, String postalCode, String city) {
        super(Customer.CUSTOMER);

        setId(id);
        setFirstName(firstName);
        setLastName(lastName);
        setStreet(street);
        setPostalCode(postalCode);
        setCity(city);
        resetChangedOnNotNull();
    }
}
