/*
 * This file is generated by jOOQ.
 */
package ch.martinelli.demo.nested.db.tables.records;


import ch.martinelli.demo.nested.db.tables.OrderItem;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrderItemRecord extends UpdatableRecordImpl<OrderItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.order_item.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.order_item.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.order_item.quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.order_item.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.order_item.purchase_order_id</code>.
     */
    public void setPurchaseOrderId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.order_item.purchase_order_id</code>.
     */
    public Long getPurchaseOrderId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.order_item.product_id</code>.
     */
    public void setProductId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.order_item.product_id</code>.
     */
    public Long getProductId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderItemRecord
     */
    public OrderItemRecord() {
        super(OrderItem.ORDER_ITEM);
    }

    /**
     * Create a detached, initialised OrderItemRecord
     */
    public OrderItemRecord(Long id, Integer quantity, Long purchaseOrderId, Long productId) {
        super(OrderItem.ORDER_ITEM);

        setId(id);
        setQuantity(quantity);
        setPurchaseOrderId(purchaseOrderId);
        setProductId(productId);
        resetChangedOnNotNull();
    }
}
