/*
 * This file is generated by jOOQ.
 */
package ch.martinelli.demo.nested.db.tables.records;


import ch.martinelli.demo.nested.db.tables.PurchaseOrder;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PurchaseOrderRecord extends UpdatableRecordImpl<PurchaseOrderRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.purchase_order.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.purchase_order.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.purchase_order.order_date</code>.
     */
    public void setOrderDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.purchase_order.order_date</code>.
     */
    public LocalDateTime getOrderDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.purchase_order.customer_id</code>.
     */
    public void setCustomerId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.purchase_order.customer_id</code>.
     */
    public Long getCustomerId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PurchaseOrderRecord
     */
    public PurchaseOrderRecord() {
        super(PurchaseOrder.PURCHASE_ORDER);
    }

    /**
     * Create a detached, initialised PurchaseOrderRecord
     */
    public PurchaseOrderRecord(Long id, LocalDateTime orderDate, Long customerId) {
        super(PurchaseOrder.PURCHASE_ORDER);

        setId(id);
        setOrderDate(orderDate);
        setCustomerId(customerId);
        resetChangedOnNotNull();
    }
}
