/*
 * This file is generated by jOOQ.
 */
package ch.martinelli.demo.nested.db;


import ch.martinelli.demo.nested.db.tables.OrderItem;
import ch.martinelli.demo.nested.db.tables.PurchaseOrder;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index UX_ORDER_ITEM_PRODUCT_ID = Internal.createIndex(DSL.name("ux_order_item_product_id"), OrderItem.ORDER_ITEM, new OrderField[] { OrderItem.ORDER_ITEM.PRODUCT_ID }, false);
    public static final Index UX_ORDER_ITEM_PURCHASE_ORDER_ID = Internal.createIndex(DSL.name("ux_order_item_purchase_order_id"), OrderItem.ORDER_ITEM, new OrderField[] { OrderItem.ORDER_ITEM.PURCHASE_ORDER_ID }, false);
    public static final Index UX_PURCHASE_ORDER_CUSTOMER_ID = Internal.createIndex(DSL.name("ux_purchase_order_customer_id"), PurchaseOrder.PURCHASE_ORDER, new OrderField[] { PurchaseOrder.PURCHASE_ORDER.CUSTOMER_ID }, false);
}
