/*
 * This file is generated by jOOQ.
 */
package ch.martinelli.demo.nested.db;


import ch.martinelli.demo.nested.db.tables.Customer;
import ch.martinelli.demo.nested.db.tables.OrderItem;
import ch.martinelli.demo.nested.db.tables.Product;
import ch.martinelli.demo.nested.db.tables.PurchaseOrder;
import ch.martinelli.demo.nested.db.tables.records.CustomerRecord;
import ch.martinelli.demo.nested.db.tables.records.OrderItemRecord;
import ch.martinelli.demo.nested.db.tables.records.ProductRecord;
import ch.martinelli.demo.nested.db.tables.records.PurchaseOrderRecord;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CustomerRecord> CUSTOMER_PKEY = Internal.createUniqueKey(Customer.CUSTOMER, DSL.name("customer_pkey"), new TableField[] { Customer.CUSTOMER.ID }, true);
    public static final UniqueKey<OrderItemRecord> ORDER_ITEM_PKEY = Internal.createUniqueKey(OrderItem.ORDER_ITEM, DSL.name("order_item_pkey"), new TableField[] { OrderItem.ORDER_ITEM.ID }, true);
    public static final UniqueKey<ProductRecord> PRODUCT_PKEY = Internal.createUniqueKey(Product.PRODUCT, DSL.name("product_pkey"), new TableField[] { Product.PRODUCT.ID }, true);
    public static final UniqueKey<PurchaseOrderRecord> PURCHASE_ORDER_PKEY = Internal.createUniqueKey(PurchaseOrder.PURCHASE_ORDER, DSL.name("purchase_order_pkey"), new TableField[] { PurchaseOrder.PURCHASE_ORDER.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<OrderItemRecord, ProductRecord> ORDER_ITEM__ORDER_ITEM_PRODUCT_ID_FKEY = Internal.createForeignKey(OrderItem.ORDER_ITEM, DSL.name("order_item_product_id_fkey"), new TableField[] { OrderItem.ORDER_ITEM.PRODUCT_ID }, Keys.PRODUCT_PKEY, new TableField[] { Product.PRODUCT.ID }, true);
    public static final ForeignKey<OrderItemRecord, PurchaseOrderRecord> ORDER_ITEM__ORDER_ITEM_PURCHASE_ORDER_ID_FKEY = Internal.createForeignKey(OrderItem.ORDER_ITEM, DSL.name("order_item_purchase_order_id_fkey"), new TableField[] { OrderItem.ORDER_ITEM.PURCHASE_ORDER_ID }, Keys.PURCHASE_ORDER_PKEY, new TableField[] { PurchaseOrder.PURCHASE_ORDER.ID }, true);
    public static final ForeignKey<PurchaseOrderRecord, CustomerRecord> PURCHASE_ORDER__PURCHASE_ORDER_CUSTOMER_ID_FKEY = Internal.createForeignKey(PurchaseOrder.PURCHASE_ORDER, DSL.name("purchase_order_customer_id_fkey"), new TableField[] { PurchaseOrder.PURCHASE_ORDER.CUSTOMER_ID }, Keys.CUSTOMER_PKEY, new TableField[] { Customer.CUSTOMER.ID }, true);
}
