/*
 * This file is generated by jOOQ.
 */
package ch.martinelli.demo.nested.db;


import ch.martinelli.demo.nested.db.tables.Customer;
import ch.martinelli.demo.nested.db.tables.OrderItem;
import ch.martinelli.demo.nested.db.tables.Product;
import ch.martinelli.demo.nested.db.tables.PurchaseOrder;
import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.customer</code>.
     */
    public final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>public.order_item</code>.
     */
    public final OrderItem ORDER_ITEM = OrderItem.ORDER_ITEM;

    /**
     * The table <code>public.product</code>.
     */
    public final Product PRODUCT = Product.PRODUCT;

    /**
     * The table <code>public.purchase_order</code>.
     */
    public final PurchaseOrder PURCHASE_ORDER = PurchaseOrder.PURCHASE_ORDER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.CUSTOMER_SEQ,
            Sequences.ORDER_ITEM_SEQ,
            Sequences.PRODUCT_SEQ,
            Sequences.PURCHASE_ORDER_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Customer.CUSTOMER,
            OrderItem.ORDER_ITEM,
            Product.PRODUCT,
            PurchaseOrder.PURCHASE_ORDER
        );
    }
}
