/*
 * This file is generated by jOOQ.
 */
package ch.martinelli.demo.nested.db;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sequences {

    /**
     * The sequence <code>public.customer_seq</code>
     */
    public static final Sequence<Long> CUSTOMER_SEQ = Internal.createSequence("customer_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), 100000, 50, null, null, false, null);

    /**
     * The sequence <code>public.order_item_seq</code>
     */
    public static final Sequence<Long> ORDER_ITEM_SEQ = Internal.createSequence("order_item_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), 100000, 50, null, null, false, null);

    /**
     * The sequence <code>public.product_seq</code>
     */
    public static final Sequence<Long> PRODUCT_SEQ = Internal.createSequence("product_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), 100000, 50, null, null, false, null);

    /**
     * The sequence <code>public.purchase_order_seq</code>
     */
    public static final Sequence<Long> PURCHASE_ORDER_SEQ = Internal.createSequence("purchase_order_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), 100000, 50, null, null, false, null);
}
