/*
 * This file is generated by jOOQ.
 */
package ch.martinelli.demo.nested.db;


import ch.martinelli.demo.nested.db.tables.Customer;
import ch.martinelli.demo.nested.db.tables.OrderItem;
import ch.martinelli.demo.nested.db.tables.Product;
import ch.martinelli.demo.nested.db.tables.PurchaseOrder;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.customer</code>.
     */
    public static final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>public.order_item</code>.
     */
    public static final OrderItem ORDER_ITEM = OrderItem.ORDER_ITEM;

    /**
     * The table <code>public.product</code>.
     */
    public static final Product PRODUCT = Product.PRODUCT;

    /**
     * The table <code>public.purchase_order</code>.
     */
    public static final PurchaseOrder PURCHASE_ORDER = PurchaseOrder.PURCHASE_ORDER;
}
